// flow-typed signature: 821f1b257ddd27f9f3660fb93a2050ff
// flow-typed version: <<STUB>>/eslint-config-universe_v^11.0.0/flow_v0.182.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-universe'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-universe' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-universe/default' {
  declare module.exports: any;
}

declare module 'eslint-config-universe/native' {
  declare module.exports: any;
}

declare module 'eslint-config-universe/node' {
  declare module.exports: any;
}

declare module 'eslint-config-universe/shared/__tests__/extensions-test' {
  declare module.exports: any;
}

declare module 'eslint-config-universe/shared/core' {
  declare module.exports: any;
}

declare module 'eslint-config-universe/shared/extensions' {
  declare module.exports: any;
}

declare module 'eslint-config-universe/shared/prettier' {
  declare module.exports: any;
}

declare module 'eslint-config-universe/shared/react' {
  declare module.exports: any;
}

declare module 'eslint-config-universe/shared/typescript-analysis' {
  declare module.exports: any;
}

declare module 'eslint-config-universe/shared/typescript' {
  declare module.exports: any;
}

declare module 'eslint-config-universe/web' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-universe/default.js' {
  declare module.exports: $Exports<'eslint-config-universe/default'>;
}
declare module 'eslint-config-universe/native.js' {
  declare module.exports: $Exports<'eslint-config-universe/native'>;
}
declare module 'eslint-config-universe/node.js' {
  declare module.exports: $Exports<'eslint-config-universe/node'>;
}
declare module 'eslint-config-universe/shared/__tests__/extensions-test.js' {
  declare module.exports: $Exports<'eslint-config-universe/shared/__tests__/extensions-test'>;
}
declare module 'eslint-config-universe/shared/core.js' {
  declare module.exports: $Exports<'eslint-config-universe/shared/core'>;
}
declare module 'eslint-config-universe/shared/extensions.js' {
  declare module.exports: $Exports<'eslint-config-universe/shared/extensions'>;
}
declare module 'eslint-config-universe/shared/prettier.js' {
  declare module.exports: $Exports<'eslint-config-universe/shared/prettier'>;
}
declare module 'eslint-config-universe/shared/react.js' {
  declare module.exports: $Exports<'eslint-config-universe/shared/react'>;
}
declare module 'eslint-config-universe/shared/typescript-analysis.js' {
  declare module.exports: $Exports<'eslint-config-universe/shared/typescript-analysis'>;
}
declare module 'eslint-config-universe/shared/typescript.js' {
  declare module.exports: $Exports<'eslint-config-universe/shared/typescript'>;
}
declare module 'eslint-config-universe/web.js' {
  declare module.exports: $Exports<'eslint-config-universe/web'>;
}
