// flow-typed signature: 701359386da0d712e79981b0e641fcab
// flow-typed version: <<STUB>>/expo-splash-screen_v~0.15.1/flow_v0.182.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-splash-screen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-splash-screen' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-splash-screen/app.plugin' {
  declare module.exports: any;
}

declare module 'expo-splash-screen/build/ExpoSplashScreen' {
  declare module.exports: any;
}

declare module 'expo-splash-screen/build/ExpoSplashScreen.web' {
  declare module.exports: any;
}

declare module 'expo-splash-screen/build' {
  declare module.exports: any;
}

declare module 'expo-splash-screen/build/SplashScreen' {
  declare module.exports: any;
}

declare module 'expo-splash-screen/plugin/build/withSplashScreen' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-splash-screen/app.plugin.js' {
  declare module.exports: $Exports<'expo-splash-screen/app.plugin'>;
}
declare module 'expo-splash-screen/build/ExpoSplashScreen.js' {
  declare module.exports: $Exports<'expo-splash-screen/build/ExpoSplashScreen'>;
}
declare module 'expo-splash-screen/build/ExpoSplashScreen.web.js' {
  declare module.exports: $Exports<'expo-splash-screen/build/ExpoSplashScreen.web'>;
}
declare module 'expo-splash-screen/build/index' {
  declare module.exports: $Exports<'expo-splash-screen/build'>;
}
declare module 'expo-splash-screen/build/index.js' {
  declare module.exports: $Exports<'expo-splash-screen/build'>;
}
declare module 'expo-splash-screen/build/SplashScreen.js' {
  declare module.exports: $Exports<'expo-splash-screen/build/SplashScreen'>;
}
declare module 'expo-splash-screen/plugin/build/withSplashScreen.js' {
  declare module.exports: $Exports<'expo-splash-screen/plugin/build/withSplashScreen'>;
}
