// flow-typed signature: 9dd215200b8dbbfc868645afdc1d97c7
// flow-typed version: <<STUB>>/expo-system-ui_v~1.2.0/flow_v0.182.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-system-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-system-ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-system-ui/app.plugin' {
  declare module.exports: any;
}

declare module 'expo-system-ui/build/ExpoSystemUI' {
  declare module.exports: any;
}

declare module 'expo-system-ui/build/ExpoSystemUI.web' {
  declare module.exports: any;
}

declare module 'expo-system-ui/build/SystemUI' {
  declare module.exports: any;
}

declare module 'expo-system-ui/plugin/build/withAndroidRootViewBackgroundColor' {
  declare module.exports: any;
}

declare module 'expo-system-ui/plugin/build/withAndroidUserInterfaceStyle' {
  declare module.exports: any;
}

declare module 'expo-system-ui/plugin/build/withIosRootViewBackgroundColor' {
  declare module.exports: any;
}

declare module 'expo-system-ui/plugin/build/withIosUserInterfaceStyle' {
  declare module.exports: any;
}

declare module 'expo-system-ui/plugin/build/withSystemUI' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-system-ui/app.plugin.js' {
  declare module.exports: $Exports<'expo-system-ui/app.plugin'>;
}
declare module 'expo-system-ui/build/ExpoSystemUI.js' {
  declare module.exports: $Exports<'expo-system-ui/build/ExpoSystemUI'>;
}
declare module 'expo-system-ui/build/ExpoSystemUI.web.js' {
  declare module.exports: $Exports<'expo-system-ui/build/ExpoSystemUI.web'>;
}
declare module 'expo-system-ui/build/SystemUI.js' {
  declare module.exports: $Exports<'expo-system-ui/build/SystemUI'>;
}
declare module 'expo-system-ui/plugin/build/withAndroidRootViewBackgroundColor.js' {
  declare module.exports: $Exports<'expo-system-ui/plugin/build/withAndroidRootViewBackgroundColor'>;
}
declare module 'expo-system-ui/plugin/build/withAndroidUserInterfaceStyle.js' {
  declare module.exports: $Exports<'expo-system-ui/plugin/build/withAndroidUserInterfaceStyle'>;
}
declare module 'expo-system-ui/plugin/build/withIosRootViewBackgroundColor.js' {
  declare module.exports: $Exports<'expo-system-ui/plugin/build/withIosRootViewBackgroundColor'>;
}
declare module 'expo-system-ui/plugin/build/withIosUserInterfaceStyle.js' {
  declare module.exports: $Exports<'expo-system-ui/plugin/build/withIosUserInterfaceStyle'>;
}
declare module 'expo-system-ui/plugin/build/withSystemUI.js' {
  declare module.exports: $Exports<'expo-system-ui/plugin/build/withSystemUI'>;
}
