// flow-typed signature: b152de4485fe136a3f3f7016886feaa8
// flow-typed version: <<STUB>>/expo-updates_v~0.13.3/flow_v0.182.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-updates'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-updates' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-updates/app.plugin' {
  declare module.exports: any;
}

declare module 'expo-updates/bin/cli' {
  declare module.exports: any;
}

declare module 'expo-updates/build-cli/cli' {
  declare module.exports: any;
}

declare module 'expo-updates/build-cli/configureCodeSigning' {
  declare module.exports: any;
}

declare module 'expo-updates/build-cli/configureCodeSigningAsync' {
  declare module.exports: any;
}

declare module 'expo-updates/build-cli/generateCodeSigning' {
  declare module.exports: any;
}

declare module 'expo-updates/build-cli/generateCodeSigningAsync' {
  declare module.exports: any;
}

declare module 'expo-updates/build-cli/utils/args' {
  declare module.exports: any;
}

declare module 'expo-updates/build-cli/utils/log' {
  declare module.exports: any;
}

declare module 'expo-updates/build-cli/utils/modifyConfigAsync' {
  declare module.exports: any;
}

declare module 'expo-updates/build/ExpoUpdates' {
  declare module.exports: any;
}

declare module 'expo-updates/build/ExpoUpdates.web' {
  declare module.exports: any;
}

declare module 'expo-updates/build' {
  declare module.exports: any;
}

declare module 'expo-updates/build/Updates' {
  declare module.exports: any;
}

declare module 'expo-updates/build/Updates.types' {
  declare module.exports: any;
}

declare module 'expo-updates/e2e/jest.config' {
  declare module.exports: any;
}

declare module 'expo-updates/jest.cli.config' {
  declare module.exports: any;
}

declare module 'expo-updates/plugin/build/withUpdates' {
  declare module.exports: any;
}

declare module 'expo-updates/plugin/jest.config' {
  declare module.exports: any;
}

declare module 'expo-updates/scripts/createManifest' {
  declare module.exports: any;
}

declare module 'expo-updates/scripts/filterPlatformAssetScales' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-updates/app.plugin.js' {
  declare module.exports: $Exports<'expo-updates/app.plugin'>;
}
declare module 'expo-updates/bin/cli.js' {
  declare module.exports: $Exports<'expo-updates/bin/cli'>;
}
declare module 'expo-updates/build-cli/cli.js' {
  declare module.exports: $Exports<'expo-updates/build-cli/cli'>;
}
declare module 'expo-updates/build-cli/configureCodeSigning.js' {
  declare module.exports: $Exports<'expo-updates/build-cli/configureCodeSigning'>;
}
declare module 'expo-updates/build-cli/configureCodeSigningAsync.js' {
  declare module.exports: $Exports<'expo-updates/build-cli/configureCodeSigningAsync'>;
}
declare module 'expo-updates/build-cli/generateCodeSigning.js' {
  declare module.exports: $Exports<'expo-updates/build-cli/generateCodeSigning'>;
}
declare module 'expo-updates/build-cli/generateCodeSigningAsync.js' {
  declare module.exports: $Exports<'expo-updates/build-cli/generateCodeSigningAsync'>;
}
declare module 'expo-updates/build-cli/utils/args.js' {
  declare module.exports: $Exports<'expo-updates/build-cli/utils/args'>;
}
declare module 'expo-updates/build-cli/utils/log.js' {
  declare module.exports: $Exports<'expo-updates/build-cli/utils/log'>;
}
declare module 'expo-updates/build-cli/utils/modifyConfigAsync.js' {
  declare module.exports: $Exports<'expo-updates/build-cli/utils/modifyConfigAsync'>;
}
declare module 'expo-updates/build/ExpoUpdates.js' {
  declare module.exports: $Exports<'expo-updates/build/ExpoUpdates'>;
}
declare module 'expo-updates/build/ExpoUpdates.web.js' {
  declare module.exports: $Exports<'expo-updates/build/ExpoUpdates.web'>;
}
declare module 'expo-updates/build/index' {
  declare module.exports: $Exports<'expo-updates/build'>;
}
declare module 'expo-updates/build/index.js' {
  declare module.exports: $Exports<'expo-updates/build'>;
}
declare module 'expo-updates/build/Updates.js' {
  declare module.exports: $Exports<'expo-updates/build/Updates'>;
}
declare module 'expo-updates/build/Updates.types.js' {
  declare module.exports: $Exports<'expo-updates/build/Updates.types'>;
}
declare module 'expo-updates/e2e/jest.config.js' {
  declare module.exports: $Exports<'expo-updates/e2e/jest.config'>;
}
declare module 'expo-updates/jest.cli.config.js' {
  declare module.exports: $Exports<'expo-updates/jest.cli.config'>;
}
declare module 'expo-updates/plugin/build/withUpdates.js' {
  declare module.exports: $Exports<'expo-updates/plugin/build/withUpdates'>;
}
declare module 'expo-updates/plugin/jest.config.js' {
  declare module.exports: $Exports<'expo-updates/plugin/jest.config'>;
}
declare module 'expo-updates/scripts/createManifest.js' {
  declare module.exports: $Exports<'expo-updates/scripts/createManifest'>;
}
declare module 'expo-updates/scripts/filterPlatformAssetScales.js' {
  declare module.exports: $Exports<'expo-updates/scripts/filterPlatformAssetScales'>;
}
