// flow-typed signature: 27886d371194a6cad7f9faac49a2a593
// flow-typed version: <<STUB>>/expo_v~45.0.0/flow_v0.182.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo/AppEntry' {
  declare module.exports: any;
}

declare module 'expo/bin/cli' {
  declare module.exports: any;
}

declare module 'expo/build/environment/DevAppContainer' {
  declare module.exports: any;
}

declare module 'expo/build/environment/DevLoadingView' {
  declare module.exports: any;
}

declare module 'expo/build/environment/getInstallationIdAsync.android' {
  declare module.exports: any;
}

declare module 'expo/build/environment/getInstallationIdAsync' {
  declare module.exports: any;
}

declare module 'expo/build/environment/getInstallationIdAsync.web' {
  declare module.exports: any;
}

declare module 'expo/build/environment/logging.fx' {
  declare module.exports: any;
}

declare module 'expo/build/environment/react-native-logs.fx' {
  declare module.exports: any;
}

declare module 'expo/build/environment/validate.fx' {
  declare module.exports: any;
}

declare module 'expo/build/environment/validatorState' {
  declare module.exports: any;
}

declare module 'expo/build/Expo.fx' {
  declare module.exports: any;
}

declare module 'expo/build/Expo.fx.web' {
  declare module.exports: any;
}

declare module 'expo/build/Expo' {
  declare module.exports: any;
}

declare module 'expo/build/launch/RecoveryProps' {
  declare module.exports: any;
}

declare module 'expo/build/launch/registerRootComponent' {
  declare module.exports: any;
}

declare module 'expo/build/launch/withExpoRoot' {
  declare module.exports: any;
}

declare module 'expo/build/launch/withExpoRoot.types' {
  declare module.exports: any;
}

declare module 'expo/build/launch/withExpoRoot.web' {
  declare module.exports: any;
}

declare module 'expo/build/logs/format/ReactNodeFormatter' {
  declare module.exports: any;
}

declare module 'expo/build/logs/Logs' {
  declare module.exports: any;
}

declare module 'expo/build/logs/Logs.web' {
  declare module.exports: any;
}

declare module 'expo/build/logs/LogSerialization' {
  declare module.exports: any;
}

declare module 'expo/build/logs/RemoteConsole' {
  declare module.exports: any;
}

declare module 'expo/build/logs/RemoteLogging' {
  declare module.exports: any;
}

declare module 'expo/build/timer/polyfillNextTick' {
  declare module.exports: any;
}

declare module 'expo/metro-config' {
  declare module.exports: any;
}

declare module 'expo/react-native.config' {
  declare module.exports: any;
}

declare module 'expo/scripts/resolveAppEntry' {
  declare module.exports: any;
}

declare module 'expo/tools/hashAssetFiles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo/AppEntry.js' {
  declare module.exports: $Exports<'expo/AppEntry'>;
}
declare module 'expo/bin/cli.js' {
  declare module.exports: $Exports<'expo/bin/cli'>;
}
declare module 'expo/build/environment/DevAppContainer.js' {
  declare module.exports: $Exports<'expo/build/environment/DevAppContainer'>;
}
declare module 'expo/build/environment/DevLoadingView.js' {
  declare module.exports: $Exports<'expo/build/environment/DevLoadingView'>;
}
declare module 'expo/build/environment/getInstallationIdAsync.android.js' {
  declare module.exports: $Exports<'expo/build/environment/getInstallationIdAsync.android'>;
}
declare module 'expo/build/environment/getInstallationIdAsync.js' {
  declare module.exports: $Exports<'expo/build/environment/getInstallationIdAsync'>;
}
declare module 'expo/build/environment/getInstallationIdAsync.web.js' {
  declare module.exports: $Exports<'expo/build/environment/getInstallationIdAsync.web'>;
}
declare module 'expo/build/environment/logging.fx.js' {
  declare module.exports: $Exports<'expo/build/environment/logging.fx'>;
}
declare module 'expo/build/environment/react-native-logs.fx.js' {
  declare module.exports: $Exports<'expo/build/environment/react-native-logs.fx'>;
}
declare module 'expo/build/environment/validate.fx.js' {
  declare module.exports: $Exports<'expo/build/environment/validate.fx'>;
}
declare module 'expo/build/environment/validatorState.js' {
  declare module.exports: $Exports<'expo/build/environment/validatorState'>;
}
declare module 'expo/build/Expo.fx.js' {
  declare module.exports: $Exports<'expo/build/Expo.fx'>;
}
declare module 'expo/build/Expo.fx.web.js' {
  declare module.exports: $Exports<'expo/build/Expo.fx.web'>;
}
declare module 'expo/build/Expo.js' {
  declare module.exports: $Exports<'expo/build/Expo'>;
}
declare module 'expo/build/launch/RecoveryProps.js' {
  declare module.exports: $Exports<'expo/build/launch/RecoveryProps'>;
}
declare module 'expo/build/launch/registerRootComponent.js' {
  declare module.exports: $Exports<'expo/build/launch/registerRootComponent'>;
}
declare module 'expo/build/launch/withExpoRoot.js' {
  declare module.exports: $Exports<'expo/build/launch/withExpoRoot'>;
}
declare module 'expo/build/launch/withExpoRoot.types.js' {
  declare module.exports: $Exports<'expo/build/launch/withExpoRoot.types'>;
}
declare module 'expo/build/launch/withExpoRoot.web.js' {
  declare module.exports: $Exports<'expo/build/launch/withExpoRoot.web'>;
}
declare module 'expo/build/logs/format/ReactNodeFormatter.js' {
  declare module.exports: $Exports<'expo/build/logs/format/ReactNodeFormatter'>;
}
declare module 'expo/build/logs/Logs.js' {
  declare module.exports: $Exports<'expo/build/logs/Logs'>;
}
declare module 'expo/build/logs/Logs.web.js' {
  declare module.exports: $Exports<'expo/build/logs/Logs.web'>;
}
declare module 'expo/build/logs/LogSerialization.js' {
  declare module.exports: $Exports<'expo/build/logs/LogSerialization'>;
}
declare module 'expo/build/logs/RemoteConsole.js' {
  declare module.exports: $Exports<'expo/build/logs/RemoteConsole'>;
}
declare module 'expo/build/logs/RemoteLogging.js' {
  declare module.exports: $Exports<'expo/build/logs/RemoteLogging'>;
}
declare module 'expo/build/timer/polyfillNextTick.js' {
  declare module.exports: $Exports<'expo/build/timer/polyfillNextTick'>;
}
declare module 'expo/metro-config.js' {
  declare module.exports: $Exports<'expo/metro-config'>;
}
declare module 'expo/react-native.config.js' {
  declare module.exports: $Exports<'expo/react-native.config'>;
}
declare module 'expo/scripts/resolveAppEntry.js' {
  declare module.exports: $Exports<'expo/scripts/resolveAppEntry'>;
}
declare module 'expo/tools/hashAssetFiles.js' {
  declare module.exports: $Exports<'expo/tools/hashAssetFiles'>;
}
