// flow-typed signature: a3ed1f85faa841bec0c2687251c055b5
// flow-typed version: <<STUB>>/react-native-gesture-handler_v~2.2.1/flow_v0.182.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-gesture-handler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-gesture-handler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-gesture-handler/jestSetup' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/components/DrawerLayout' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/components/GestureButtons' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/components/GestureComponents' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/components/GestureComponents.web' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/components/GestureHandlerButton' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/components/GestureHandlerButton.web' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/components/Swipeable' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/components/touchables/GenericTouchable' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/components/touchables' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/components/touchables/TouchableHighlight' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/components/touchables/TouchableNativeFeedback.android' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/components/touchables/TouchableNativeFeedback' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/components/touchables/TouchableOpacity' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/components/touchables/TouchableWithoutFeedback' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/Directions' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/EventType' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/gestureHandlerRootHOC' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/GestureHandlerRootView.android' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/GestureHandlerRootView' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/handlers/createHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/handlers/createNativeWrapper' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/handlers/FlingGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/handlers/ForceTouchGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/handlers/gestureHandlerCommon' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/handlers/gestureHandlerTypesCompat' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/handlers/gestures/eventReceiver' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/handlers/gestures/flingGesture' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/handlers/gestures/forceTouchGesture' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/handlers/gestures/gesture' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/handlers/gestures/gestureComposition' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/handlers/gestures/GestureDetector' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/handlers/gestures/gestureObjects' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/handlers/gestures/gestureStateManager' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/handlers/gestures/longPressGesture' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/handlers/gestures/manualGesture' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/handlers/gestures/nativeGesture' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/handlers/gestures/panGesture' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/handlers/gestures/pinchGesture' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/handlers/gestures/reanimatedWrapper' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/handlers/gestures/rotationGesture' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/handlers/gestures/tapGesture' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/handlers/handlersRegistry' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/handlers/LongPressGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/handlers/NativeViewGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/handlers/PanGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/handlers/PinchGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/handlers/RotationGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/handlers/TapGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/init' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/mocks' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/PlatformConstants' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/PlatformConstants.web' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/RNGestureHandlerModule' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/RNGestureHandlerModule.web' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/State' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/typeUtils' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/utils' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/web/constants' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/web/DiscreteGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/web/DraggingGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/web/Errors' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/web/FlingGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/web/GestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/web/IndiscreteGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/web/LongPressGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/web/NativeViewGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/web/NodeManager' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/web/PanGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/web/PinchGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/web/PressGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/web/RotationGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/web/TapGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/commonjs/web/utils' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/components/DrawerLayout' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/components/GestureButtons' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/components/GestureComponents' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/components/GestureComponents.web' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/components/GestureHandlerButton' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/components/GestureHandlerButton.web' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/components/Swipeable' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/components/touchables/GenericTouchable' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/components/touchables' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/components/touchables/TouchableHighlight' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/components/touchables/TouchableNativeFeedback.android' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/components/touchables/TouchableNativeFeedback' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/components/touchables/TouchableOpacity' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/components/touchables/TouchableWithoutFeedback' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/Directions' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/EventType' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/gestureHandlerRootHOC' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/GestureHandlerRootView.android' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/GestureHandlerRootView' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/handlers/createHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/handlers/createNativeWrapper' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/handlers/FlingGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/handlers/ForceTouchGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/handlers/gestureHandlerCommon' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/handlers/gestureHandlerTypesCompat' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/handlers/gestures/eventReceiver' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/handlers/gestures/flingGesture' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/handlers/gestures/forceTouchGesture' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/handlers/gestures/gesture' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/handlers/gestures/gestureComposition' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/handlers/gestures/GestureDetector' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/handlers/gestures/gestureObjects' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/handlers/gestures/gestureStateManager' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/handlers/gestures/longPressGesture' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/handlers/gestures/manualGesture' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/handlers/gestures/nativeGesture' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/handlers/gestures/panGesture' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/handlers/gestures/pinchGesture' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/handlers/gestures/reanimatedWrapper' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/handlers/gestures/rotationGesture' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/handlers/gestures/tapGesture' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/handlers/handlersRegistry' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/handlers/LongPressGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/handlers/NativeViewGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/handlers/PanGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/handlers/PinchGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/handlers/RotationGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/handlers/TapGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/init' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/mocks' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/PlatformConstants' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/PlatformConstants.web' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/RNGestureHandlerModule' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/RNGestureHandlerModule.web' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/State' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/typeUtils' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/utils' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/web/constants' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/web/DiscreteGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/web/DraggingGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/web/Errors' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/web/FlingGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/web/GestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/web/IndiscreteGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/web/LongPressGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/web/NativeViewGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/web/NodeManager' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/web/PanGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/web/PinchGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/web/PressGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/web/RotationGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/web/TapGestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/lib/module/web/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-gesture-handler/jestSetup.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/jestSetup'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/components/DrawerLayout.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/components/DrawerLayout'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/components/GestureButtons.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/components/GestureButtons'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/components/GestureComponents.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/components/GestureComponents'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/components/GestureComponents.web.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/components/GestureComponents.web'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/components/GestureHandlerButton.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/components/GestureHandlerButton'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/components/GestureHandlerButton.web.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/components/GestureHandlerButton.web'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/components/Swipeable.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/components/Swipeable'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/components/touchables/GenericTouchable.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/components/touchables/GenericTouchable'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/components/touchables/index' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/components/touchables'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/components/touchables/index.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/components/touchables'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/components/touchables/TouchableHighlight.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/components/touchables/TouchableHighlight'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/components/touchables/TouchableNativeFeedback.android.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/components/touchables/TouchableNativeFeedback.android'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/components/touchables/TouchableNativeFeedback.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/components/touchables/TouchableNativeFeedback'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/components/touchables/TouchableOpacity.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/components/touchables/TouchableOpacity'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/components/touchables/TouchableWithoutFeedback.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/components/touchables/TouchableWithoutFeedback'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/Directions.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/Directions'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/EventType.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/EventType'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/gestureHandlerRootHOC.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/gestureHandlerRootHOC'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/GestureHandlerRootView.android.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/GestureHandlerRootView.android'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/GestureHandlerRootView.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/GestureHandlerRootView'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/handlers/createHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/handlers/createHandler'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/handlers/createNativeWrapper.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/handlers/createNativeWrapper'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/handlers/FlingGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/handlers/FlingGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/handlers/ForceTouchGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/handlers/ForceTouchGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/handlers/gestureHandlerCommon.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/handlers/gestureHandlerCommon'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/handlers/gestureHandlerTypesCompat.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/handlers/gestureHandlerTypesCompat'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/handlers/gestures/eventReceiver.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/handlers/gestures/eventReceiver'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/handlers/gestures/flingGesture.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/handlers/gestures/flingGesture'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/handlers/gestures/forceTouchGesture.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/handlers/gestures/forceTouchGesture'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/handlers/gestures/gesture.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/handlers/gestures/gesture'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/handlers/gestures/gestureComposition.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/handlers/gestures/gestureComposition'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/handlers/gestures/GestureDetector.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/handlers/gestures/GestureDetector'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/handlers/gestures/gestureObjects.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/handlers/gestures/gestureObjects'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/handlers/gestures/gestureStateManager.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/handlers/gestures/gestureStateManager'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/handlers/gestures/longPressGesture.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/handlers/gestures/longPressGesture'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/handlers/gestures/manualGesture.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/handlers/gestures/manualGesture'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/handlers/gestures/nativeGesture.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/handlers/gestures/nativeGesture'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/handlers/gestures/panGesture.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/handlers/gestures/panGesture'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/handlers/gestures/pinchGesture.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/handlers/gestures/pinchGesture'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/handlers/gestures/reanimatedWrapper.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/handlers/gestures/reanimatedWrapper'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/handlers/gestures/rotationGesture.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/handlers/gestures/rotationGesture'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/handlers/gestures/tapGesture.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/handlers/gestures/tapGesture'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/handlers/handlersRegistry.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/handlers/handlersRegistry'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/handlers/LongPressGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/handlers/LongPressGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/handlers/NativeViewGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/handlers/NativeViewGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/handlers/PanGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/handlers/PanGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/handlers/PinchGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/handlers/PinchGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/handlers/RotationGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/handlers/RotationGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/handlers/TapGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/handlers/TapGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/index' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/index.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/init.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/init'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/mocks.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/mocks'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/PlatformConstants.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/PlatformConstants'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/PlatformConstants.web.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/PlatformConstants.web'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/RNGestureHandlerModule.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/RNGestureHandlerModule'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/RNGestureHandlerModule.web.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/RNGestureHandlerModule.web'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/State.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/State'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/typeUtils.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/typeUtils'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/utils.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/utils'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/web/constants.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/web/constants'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/web/DiscreteGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/web/DiscreteGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/web/DraggingGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/web/DraggingGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/web/Errors.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/web/Errors'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/web/FlingGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/web/FlingGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/web/GestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/web/GestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/web/IndiscreteGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/web/IndiscreteGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/web/LongPressGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/web/LongPressGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/web/NativeViewGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/web/NativeViewGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/web/NodeManager.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/web/NodeManager'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/web/PanGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/web/PanGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/web/PinchGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/web/PinchGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/web/PressGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/web/PressGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/web/RotationGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/web/RotationGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/web/TapGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/web/TapGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/commonjs/web/utils.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/commonjs/web/utils'>;
}
declare module 'react-native-gesture-handler/lib/module/components/DrawerLayout.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/components/DrawerLayout'>;
}
declare module 'react-native-gesture-handler/lib/module/components/GestureButtons.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/components/GestureButtons'>;
}
declare module 'react-native-gesture-handler/lib/module/components/GestureComponents.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/components/GestureComponents'>;
}
declare module 'react-native-gesture-handler/lib/module/components/GestureComponents.web.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/components/GestureComponents.web'>;
}
declare module 'react-native-gesture-handler/lib/module/components/GestureHandlerButton.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/components/GestureHandlerButton'>;
}
declare module 'react-native-gesture-handler/lib/module/components/GestureHandlerButton.web.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/components/GestureHandlerButton.web'>;
}
declare module 'react-native-gesture-handler/lib/module/components/Swipeable.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/components/Swipeable'>;
}
declare module 'react-native-gesture-handler/lib/module/components/touchables/GenericTouchable.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/components/touchables/GenericTouchable'>;
}
declare module 'react-native-gesture-handler/lib/module/components/touchables/index' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/components/touchables'>;
}
declare module 'react-native-gesture-handler/lib/module/components/touchables/index.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/components/touchables'>;
}
declare module 'react-native-gesture-handler/lib/module/components/touchables/TouchableHighlight.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/components/touchables/TouchableHighlight'>;
}
declare module 'react-native-gesture-handler/lib/module/components/touchables/TouchableNativeFeedback.android.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/components/touchables/TouchableNativeFeedback.android'>;
}
declare module 'react-native-gesture-handler/lib/module/components/touchables/TouchableNativeFeedback.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/components/touchables/TouchableNativeFeedback'>;
}
declare module 'react-native-gesture-handler/lib/module/components/touchables/TouchableOpacity.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/components/touchables/TouchableOpacity'>;
}
declare module 'react-native-gesture-handler/lib/module/components/touchables/TouchableWithoutFeedback.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/components/touchables/TouchableWithoutFeedback'>;
}
declare module 'react-native-gesture-handler/lib/module/Directions.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/Directions'>;
}
declare module 'react-native-gesture-handler/lib/module/EventType.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/EventType'>;
}
declare module 'react-native-gesture-handler/lib/module/gestureHandlerRootHOC.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/gestureHandlerRootHOC'>;
}
declare module 'react-native-gesture-handler/lib/module/GestureHandlerRootView.android.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/GestureHandlerRootView.android'>;
}
declare module 'react-native-gesture-handler/lib/module/GestureHandlerRootView.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/GestureHandlerRootView'>;
}
declare module 'react-native-gesture-handler/lib/module/handlers/createHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/handlers/createHandler'>;
}
declare module 'react-native-gesture-handler/lib/module/handlers/createNativeWrapper.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/handlers/createNativeWrapper'>;
}
declare module 'react-native-gesture-handler/lib/module/handlers/FlingGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/handlers/FlingGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/module/handlers/ForceTouchGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/handlers/ForceTouchGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/module/handlers/gestureHandlerCommon.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/handlers/gestureHandlerCommon'>;
}
declare module 'react-native-gesture-handler/lib/module/handlers/gestureHandlerTypesCompat.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/handlers/gestureHandlerTypesCompat'>;
}
declare module 'react-native-gesture-handler/lib/module/handlers/gestures/eventReceiver.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/handlers/gestures/eventReceiver'>;
}
declare module 'react-native-gesture-handler/lib/module/handlers/gestures/flingGesture.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/handlers/gestures/flingGesture'>;
}
declare module 'react-native-gesture-handler/lib/module/handlers/gestures/forceTouchGesture.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/handlers/gestures/forceTouchGesture'>;
}
declare module 'react-native-gesture-handler/lib/module/handlers/gestures/gesture.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/handlers/gestures/gesture'>;
}
declare module 'react-native-gesture-handler/lib/module/handlers/gestures/gestureComposition.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/handlers/gestures/gestureComposition'>;
}
declare module 'react-native-gesture-handler/lib/module/handlers/gestures/GestureDetector.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/handlers/gestures/GestureDetector'>;
}
declare module 'react-native-gesture-handler/lib/module/handlers/gestures/gestureObjects.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/handlers/gestures/gestureObjects'>;
}
declare module 'react-native-gesture-handler/lib/module/handlers/gestures/gestureStateManager.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/handlers/gestures/gestureStateManager'>;
}
declare module 'react-native-gesture-handler/lib/module/handlers/gestures/longPressGesture.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/handlers/gestures/longPressGesture'>;
}
declare module 'react-native-gesture-handler/lib/module/handlers/gestures/manualGesture.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/handlers/gestures/manualGesture'>;
}
declare module 'react-native-gesture-handler/lib/module/handlers/gestures/nativeGesture.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/handlers/gestures/nativeGesture'>;
}
declare module 'react-native-gesture-handler/lib/module/handlers/gestures/panGesture.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/handlers/gestures/panGesture'>;
}
declare module 'react-native-gesture-handler/lib/module/handlers/gestures/pinchGesture.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/handlers/gestures/pinchGesture'>;
}
declare module 'react-native-gesture-handler/lib/module/handlers/gestures/reanimatedWrapper.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/handlers/gestures/reanimatedWrapper'>;
}
declare module 'react-native-gesture-handler/lib/module/handlers/gestures/rotationGesture.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/handlers/gestures/rotationGesture'>;
}
declare module 'react-native-gesture-handler/lib/module/handlers/gestures/tapGesture.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/handlers/gestures/tapGesture'>;
}
declare module 'react-native-gesture-handler/lib/module/handlers/handlersRegistry.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/handlers/handlersRegistry'>;
}
declare module 'react-native-gesture-handler/lib/module/handlers/LongPressGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/handlers/LongPressGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/module/handlers/NativeViewGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/handlers/NativeViewGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/module/handlers/PanGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/handlers/PanGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/module/handlers/PinchGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/handlers/PinchGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/module/handlers/RotationGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/handlers/RotationGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/module/handlers/TapGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/handlers/TapGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/module/index' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module'>;
}
declare module 'react-native-gesture-handler/lib/module/index.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module'>;
}
declare module 'react-native-gesture-handler/lib/module/init.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/init'>;
}
declare module 'react-native-gesture-handler/lib/module/mocks.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/mocks'>;
}
declare module 'react-native-gesture-handler/lib/module/PlatformConstants.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/PlatformConstants'>;
}
declare module 'react-native-gesture-handler/lib/module/PlatformConstants.web.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/PlatformConstants.web'>;
}
declare module 'react-native-gesture-handler/lib/module/RNGestureHandlerModule.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/RNGestureHandlerModule'>;
}
declare module 'react-native-gesture-handler/lib/module/RNGestureHandlerModule.web.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/RNGestureHandlerModule.web'>;
}
declare module 'react-native-gesture-handler/lib/module/State.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/State'>;
}
declare module 'react-native-gesture-handler/lib/module/typeUtils.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/typeUtils'>;
}
declare module 'react-native-gesture-handler/lib/module/utils.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/utils'>;
}
declare module 'react-native-gesture-handler/lib/module/web/constants.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/web/constants'>;
}
declare module 'react-native-gesture-handler/lib/module/web/DiscreteGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/web/DiscreteGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/module/web/DraggingGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/web/DraggingGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/module/web/Errors.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/web/Errors'>;
}
declare module 'react-native-gesture-handler/lib/module/web/FlingGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/web/FlingGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/module/web/GestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/web/GestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/module/web/IndiscreteGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/web/IndiscreteGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/module/web/LongPressGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/web/LongPressGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/module/web/NativeViewGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/web/NativeViewGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/module/web/NodeManager.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/web/NodeManager'>;
}
declare module 'react-native-gesture-handler/lib/module/web/PanGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/web/PanGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/module/web/PinchGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/web/PinchGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/module/web/PressGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/web/PressGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/module/web/RotationGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/web/RotationGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/module/web/TapGestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/web/TapGestureHandler'>;
}
declare module 'react-native-gesture-handler/lib/module/web/utils.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/lib/module/web/utils'>;
}
