// flow-typed signature: 23a777225612ea6e69ff515120eb8806
// flow-typed version: <<STUB>>/react-native-redash_v^18.0.0/flow_v0.182.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-redash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-redash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-redash/lib/module/Animations' {
  declare module.exports: any;
}

declare module 'react-native-redash/lib/module/Array' {
  declare module.exports: any;
}

declare module 'react-native-redash/lib/module/Colors' {
  declare module.exports: any;
}

declare module 'react-native-redash/lib/module/Coordinates' {
  declare module.exports: any;
}

declare module 'react-native-redash/lib/module/index.d' {
  declare module.exports: any;
}

declare module 'react-native-redash/lib/module' {
  declare module.exports: any;
}

declare module 'react-native-redash/lib/module/Math' {
  declare module.exports: any;
}

declare module 'react-native-redash/lib/module/Matrix3' {
  declare module.exports: any;
}

declare module 'react-native-redash/lib/module/Matrix4' {
  declare module.exports: any;
}

declare module 'react-native-redash/lib/module/Paths' {
  declare module.exports: any;
}

declare module 'react-native-redash/lib/module/Physics' {
  declare module.exports: any;
}

declare module 'react-native-redash/lib/module/ReText' {
  declare module.exports: any;
}

declare module 'react-native-redash/lib/module/Transforms' {
  declare module.exports: any;
}

declare module 'react-native-redash/lib/module/Transitions' {
  declare module.exports: any;
}

declare module 'react-native-redash/lib/module/Vectors' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-redash/lib/module/Animations.js' {
  declare module.exports: $Exports<'react-native-redash/lib/module/Animations'>;
}
declare module 'react-native-redash/lib/module/Array.js' {
  declare module.exports: $Exports<'react-native-redash/lib/module/Array'>;
}
declare module 'react-native-redash/lib/module/Colors.js' {
  declare module.exports: $Exports<'react-native-redash/lib/module/Colors'>;
}
declare module 'react-native-redash/lib/module/Coordinates.js' {
  declare module.exports: $Exports<'react-native-redash/lib/module/Coordinates'>;
}
declare module 'react-native-redash/lib/module/index.d.js' {
  declare module.exports: $Exports<'react-native-redash/lib/module/index.d'>;
}
declare module 'react-native-redash/lib/module/index' {
  declare module.exports: $Exports<'react-native-redash/lib/module'>;
}
declare module 'react-native-redash/lib/module/index.js' {
  declare module.exports: $Exports<'react-native-redash/lib/module'>;
}
declare module 'react-native-redash/lib/module/Math.js' {
  declare module.exports: $Exports<'react-native-redash/lib/module/Math'>;
}
declare module 'react-native-redash/lib/module/Matrix3.js' {
  declare module.exports: $Exports<'react-native-redash/lib/module/Matrix3'>;
}
declare module 'react-native-redash/lib/module/Matrix4.js' {
  declare module.exports: $Exports<'react-native-redash/lib/module/Matrix4'>;
}
declare module 'react-native-redash/lib/module/Paths.js' {
  declare module.exports: $Exports<'react-native-redash/lib/module/Paths'>;
}
declare module 'react-native-redash/lib/module/Physics.js' {
  declare module.exports: $Exports<'react-native-redash/lib/module/Physics'>;
}
declare module 'react-native-redash/lib/module/ReText.js' {
  declare module.exports: $Exports<'react-native-redash/lib/module/ReText'>;
}
declare module 'react-native-redash/lib/module/Transforms.js' {
  declare module.exports: $Exports<'react-native-redash/lib/module/Transforms'>;
}
declare module 'react-native-redash/lib/module/Transitions.js' {
  declare module.exports: $Exports<'react-native-redash/lib/module/Transitions'>;
}
declare module 'react-native-redash/lib/module/Vectors.js' {
  declare module.exports: $Exports<'react-native-redash/lib/module/Vectors'>;
}
