// flow-typed signature: 40d3b9e2ac9ca8d74675f658da0293af
// flow-typed version: <<STUB>>/react-native-safe-area-context_v4.2.4/flow_v0.182.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-safe-area-context'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-safe-area-context' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-safe-area-context/jest/mock' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/commonjs/CompatNativeSafeAreaProvider' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/commonjs' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/commonjs/InitialWindow' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/commonjs/InitialWindow.native' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/commonjs/NativeSafeAreaProvider' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/commonjs/NativeSafeAreaProvider.macos' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/commonjs/NativeSafeAreaProvider.web' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/commonjs/NativeSafeAreaProvider.windows' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/commonjs/SafeArea.types' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/commonjs/SafeAreaContext' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/commonjs/SafeAreaView' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/commonjs/SafeAreaView.macos' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/commonjs/SafeAreaView.web' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/commonjs/SafeAreaView.windows' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/commonjs/specs/NativeSafeAreaContext.d' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/commonjs/specs/NativeSafeAreaContext' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/commonjs/specs/NativeSafeAreaProvider.d' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/commonjs/specs/NativeSafeAreaProvider' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/commonjs/specs/NativeSafeAreaView.d' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/commonjs/specs/NativeSafeAreaView' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/commonjs/useWindowDimensions' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/module/CompatNativeSafeAreaProvider' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/module' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/module/InitialWindow' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/module/InitialWindow.native' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/module/NativeSafeAreaProvider' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/module/NativeSafeAreaProvider.macos' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/module/NativeSafeAreaProvider.web' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/module/NativeSafeAreaProvider.windows' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/module/SafeArea.types' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/module/SafeAreaContext' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/module/SafeAreaView' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/module/SafeAreaView.macos' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/module/SafeAreaView.web' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/module/SafeAreaView.windows' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/module/specs/NativeSafeAreaContext.d' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/module/specs/NativeSafeAreaContext' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/module/specs/NativeSafeAreaProvider.d' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/module/specs/NativeSafeAreaProvider' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/module/specs/NativeSafeAreaView.d' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/module/specs/NativeSafeAreaView' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/module/useWindowDimensions' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/react-native.config' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/src/specs/NativeSafeAreaContext' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/src/specs/NativeSafeAreaProvider' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/src/specs/NativeSafeAreaView' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-safe-area-context/jest/mock.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/jest/mock'>;
}
declare module 'react-native-safe-area-context/lib/commonjs/CompatNativeSafeAreaProvider.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/commonjs/CompatNativeSafeAreaProvider'>;
}
declare module 'react-native-safe-area-context/lib/commonjs/index' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/commonjs'>;
}
declare module 'react-native-safe-area-context/lib/commonjs/index.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/commonjs'>;
}
declare module 'react-native-safe-area-context/lib/commonjs/InitialWindow.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/commonjs/InitialWindow'>;
}
declare module 'react-native-safe-area-context/lib/commonjs/InitialWindow.native.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/commonjs/InitialWindow.native'>;
}
declare module 'react-native-safe-area-context/lib/commonjs/NativeSafeAreaProvider.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/commonjs/NativeSafeAreaProvider'>;
}
declare module 'react-native-safe-area-context/lib/commonjs/NativeSafeAreaProvider.macos.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/commonjs/NativeSafeAreaProvider.macos'>;
}
declare module 'react-native-safe-area-context/lib/commonjs/NativeSafeAreaProvider.web.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/commonjs/NativeSafeAreaProvider.web'>;
}
declare module 'react-native-safe-area-context/lib/commonjs/NativeSafeAreaProvider.windows.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/commonjs/NativeSafeAreaProvider.windows'>;
}
declare module 'react-native-safe-area-context/lib/commonjs/SafeArea.types.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/commonjs/SafeArea.types'>;
}
declare module 'react-native-safe-area-context/lib/commonjs/SafeAreaContext.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/commonjs/SafeAreaContext'>;
}
declare module 'react-native-safe-area-context/lib/commonjs/SafeAreaView.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/commonjs/SafeAreaView'>;
}
declare module 'react-native-safe-area-context/lib/commonjs/SafeAreaView.macos.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/commonjs/SafeAreaView.macos'>;
}
declare module 'react-native-safe-area-context/lib/commonjs/SafeAreaView.web.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/commonjs/SafeAreaView.web'>;
}
declare module 'react-native-safe-area-context/lib/commonjs/SafeAreaView.windows.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/commonjs/SafeAreaView.windows'>;
}
declare module 'react-native-safe-area-context/lib/commonjs/specs/NativeSafeAreaContext.d.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/commonjs/specs/NativeSafeAreaContext.d'>;
}
declare module 'react-native-safe-area-context/lib/commonjs/specs/NativeSafeAreaContext.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/commonjs/specs/NativeSafeAreaContext'>;
}
declare module 'react-native-safe-area-context/lib/commonjs/specs/NativeSafeAreaProvider.d.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/commonjs/specs/NativeSafeAreaProvider.d'>;
}
declare module 'react-native-safe-area-context/lib/commonjs/specs/NativeSafeAreaProvider.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/commonjs/specs/NativeSafeAreaProvider'>;
}
declare module 'react-native-safe-area-context/lib/commonjs/specs/NativeSafeAreaView.d.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/commonjs/specs/NativeSafeAreaView.d'>;
}
declare module 'react-native-safe-area-context/lib/commonjs/specs/NativeSafeAreaView.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/commonjs/specs/NativeSafeAreaView'>;
}
declare module 'react-native-safe-area-context/lib/commonjs/useWindowDimensions.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/commonjs/useWindowDimensions'>;
}
declare module 'react-native-safe-area-context/lib/module/CompatNativeSafeAreaProvider.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/module/CompatNativeSafeAreaProvider'>;
}
declare module 'react-native-safe-area-context/lib/module/index' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/module'>;
}
declare module 'react-native-safe-area-context/lib/module/index.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/module'>;
}
declare module 'react-native-safe-area-context/lib/module/InitialWindow.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/module/InitialWindow'>;
}
declare module 'react-native-safe-area-context/lib/module/InitialWindow.native.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/module/InitialWindow.native'>;
}
declare module 'react-native-safe-area-context/lib/module/NativeSafeAreaProvider.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/module/NativeSafeAreaProvider'>;
}
declare module 'react-native-safe-area-context/lib/module/NativeSafeAreaProvider.macos.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/module/NativeSafeAreaProvider.macos'>;
}
declare module 'react-native-safe-area-context/lib/module/NativeSafeAreaProvider.web.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/module/NativeSafeAreaProvider.web'>;
}
declare module 'react-native-safe-area-context/lib/module/NativeSafeAreaProvider.windows.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/module/NativeSafeAreaProvider.windows'>;
}
declare module 'react-native-safe-area-context/lib/module/SafeArea.types.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/module/SafeArea.types'>;
}
declare module 'react-native-safe-area-context/lib/module/SafeAreaContext.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/module/SafeAreaContext'>;
}
declare module 'react-native-safe-area-context/lib/module/SafeAreaView.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/module/SafeAreaView'>;
}
declare module 'react-native-safe-area-context/lib/module/SafeAreaView.macos.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/module/SafeAreaView.macos'>;
}
declare module 'react-native-safe-area-context/lib/module/SafeAreaView.web.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/module/SafeAreaView.web'>;
}
declare module 'react-native-safe-area-context/lib/module/SafeAreaView.windows.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/module/SafeAreaView.windows'>;
}
declare module 'react-native-safe-area-context/lib/module/specs/NativeSafeAreaContext.d.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/module/specs/NativeSafeAreaContext.d'>;
}
declare module 'react-native-safe-area-context/lib/module/specs/NativeSafeAreaContext.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/module/specs/NativeSafeAreaContext'>;
}
declare module 'react-native-safe-area-context/lib/module/specs/NativeSafeAreaProvider.d.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/module/specs/NativeSafeAreaProvider.d'>;
}
declare module 'react-native-safe-area-context/lib/module/specs/NativeSafeAreaProvider.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/module/specs/NativeSafeAreaProvider'>;
}
declare module 'react-native-safe-area-context/lib/module/specs/NativeSafeAreaView.d.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/module/specs/NativeSafeAreaView.d'>;
}
declare module 'react-native-safe-area-context/lib/module/specs/NativeSafeAreaView.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/module/specs/NativeSafeAreaView'>;
}
declare module 'react-native-safe-area-context/lib/module/useWindowDimensions.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/module/useWindowDimensions'>;
}
declare module 'react-native-safe-area-context/react-native.config.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/react-native.config'>;
}
declare module 'react-native-safe-area-context/src/specs/NativeSafeAreaContext.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/src/specs/NativeSafeAreaContext'>;
}
declare module 'react-native-safe-area-context/src/specs/NativeSafeAreaProvider.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/src/specs/NativeSafeAreaProvider'>;
}
declare module 'react-native-safe-area-context/src/specs/NativeSafeAreaView.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/src/specs/NativeSafeAreaView'>;
}
