// flow-typed signature: b23ee46c3a7854f3c127e885c4d85659
// flow-typed version: <<STUB>>/twrnc_v^3.3.3/flow_v0.182.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'twrnc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'twrnc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'twrnc/dist/cjs/cache' {
  declare module.exports: any;
}

declare module 'twrnc/dist/cjs/ClassParser' {
  declare module.exports: any;
}

declare module 'twrnc/dist/cjs/create' {
  declare module.exports: any;
}

declare module 'twrnc/dist/cjs/helpers' {
  declare module.exports: any;
}

declare module 'twrnc/dist/cjs/hooks' {
  declare module.exports: any;
}

declare module 'twrnc/dist/cjs' {
  declare module.exports: any;
}

declare module 'twrnc/dist/cjs/parse-inputs' {
  declare module.exports: any;
}

declare module 'twrnc/dist/cjs/plugin' {
  declare module.exports: any;
}

declare module 'twrnc/dist/cjs/resolve/borders' {
  declare module.exports: any;
}

declare module 'twrnc/dist/cjs/resolve/color' {
  declare module.exports: any;
}

declare module 'twrnc/dist/cjs/resolve/flex' {
  declare module.exports: any;
}

declare module 'twrnc/dist/cjs/resolve/font-family' {
  declare module.exports: any;
}

declare module 'twrnc/dist/cjs/resolve/font-size' {
  declare module.exports: any;
}

declare module 'twrnc/dist/cjs/resolve/inset' {
  declare module.exports: any;
}

declare module 'twrnc/dist/cjs/resolve/letter-spacing' {
  declare module.exports: any;
}

declare module 'twrnc/dist/cjs/resolve/line-height' {
  declare module.exports: any;
}

declare module 'twrnc/dist/cjs/resolve/opacity' {
  declare module.exports: any;
}

declare module 'twrnc/dist/cjs/resolve/shadow' {
  declare module.exports: any;
}

declare module 'twrnc/dist/cjs/resolve/spacing' {
  declare module.exports: any;
}

declare module 'twrnc/dist/cjs/resolve/width-height' {
  declare module.exports: any;
}

declare module 'twrnc/dist/cjs/screens' {
  declare module.exports: any;
}

declare module 'twrnc/dist/cjs/styles' {
  declare module.exports: any;
}

declare module 'twrnc/dist/cjs/tw-config' {
  declare module.exports: any;
}

declare module 'twrnc/dist/cjs/types' {
  declare module.exports: any;
}

declare module 'twrnc/dist/esm/cache' {
  declare module.exports: any;
}

declare module 'twrnc/dist/esm/ClassParser' {
  declare module.exports: any;
}

declare module 'twrnc/dist/esm/create' {
  declare module.exports: any;
}

declare module 'twrnc/dist/esm/helpers' {
  declare module.exports: any;
}

declare module 'twrnc/dist/esm/hooks' {
  declare module.exports: any;
}

declare module 'twrnc/dist/esm' {
  declare module.exports: any;
}

declare module 'twrnc/dist/esm/parse-inputs' {
  declare module.exports: any;
}

declare module 'twrnc/dist/esm/plugin' {
  declare module.exports: any;
}

declare module 'twrnc/dist/esm/resolve/borders' {
  declare module.exports: any;
}

declare module 'twrnc/dist/esm/resolve/color' {
  declare module.exports: any;
}

declare module 'twrnc/dist/esm/resolve/flex' {
  declare module.exports: any;
}

declare module 'twrnc/dist/esm/resolve/font-family' {
  declare module.exports: any;
}

declare module 'twrnc/dist/esm/resolve/font-size' {
  declare module.exports: any;
}

declare module 'twrnc/dist/esm/resolve/inset' {
  declare module.exports: any;
}

declare module 'twrnc/dist/esm/resolve/letter-spacing' {
  declare module.exports: any;
}

declare module 'twrnc/dist/esm/resolve/line-height' {
  declare module.exports: any;
}

declare module 'twrnc/dist/esm/resolve/opacity' {
  declare module.exports: any;
}

declare module 'twrnc/dist/esm/resolve/shadow' {
  declare module.exports: any;
}

declare module 'twrnc/dist/esm/resolve/spacing' {
  declare module.exports: any;
}

declare module 'twrnc/dist/esm/resolve/width-height' {
  declare module.exports: any;
}

declare module 'twrnc/dist/esm/screens' {
  declare module.exports: any;
}

declare module 'twrnc/dist/esm/styles' {
  declare module.exports: any;
}

declare module 'twrnc/dist/esm/tw-config' {
  declare module.exports: any;
}

declare module 'twrnc/dist/esm/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'twrnc/dist/cjs/cache.js' {
  declare module.exports: $Exports<'twrnc/dist/cjs/cache'>;
}
declare module 'twrnc/dist/cjs/ClassParser.js' {
  declare module.exports: $Exports<'twrnc/dist/cjs/ClassParser'>;
}
declare module 'twrnc/dist/cjs/create.js' {
  declare module.exports: $Exports<'twrnc/dist/cjs/create'>;
}
declare module 'twrnc/dist/cjs/helpers.js' {
  declare module.exports: $Exports<'twrnc/dist/cjs/helpers'>;
}
declare module 'twrnc/dist/cjs/hooks.js' {
  declare module.exports: $Exports<'twrnc/dist/cjs/hooks'>;
}
declare module 'twrnc/dist/cjs/index' {
  declare module.exports: $Exports<'twrnc/dist/cjs'>;
}
declare module 'twrnc/dist/cjs/index.js' {
  declare module.exports: $Exports<'twrnc/dist/cjs'>;
}
declare module 'twrnc/dist/cjs/parse-inputs.js' {
  declare module.exports: $Exports<'twrnc/dist/cjs/parse-inputs'>;
}
declare module 'twrnc/dist/cjs/plugin.js' {
  declare module.exports: $Exports<'twrnc/dist/cjs/plugin'>;
}
declare module 'twrnc/dist/cjs/resolve/borders.js' {
  declare module.exports: $Exports<'twrnc/dist/cjs/resolve/borders'>;
}
declare module 'twrnc/dist/cjs/resolve/color.js' {
  declare module.exports: $Exports<'twrnc/dist/cjs/resolve/color'>;
}
declare module 'twrnc/dist/cjs/resolve/flex.js' {
  declare module.exports: $Exports<'twrnc/dist/cjs/resolve/flex'>;
}
declare module 'twrnc/dist/cjs/resolve/font-family.js' {
  declare module.exports: $Exports<'twrnc/dist/cjs/resolve/font-family'>;
}
declare module 'twrnc/dist/cjs/resolve/font-size.js' {
  declare module.exports: $Exports<'twrnc/dist/cjs/resolve/font-size'>;
}
declare module 'twrnc/dist/cjs/resolve/inset.js' {
  declare module.exports: $Exports<'twrnc/dist/cjs/resolve/inset'>;
}
declare module 'twrnc/dist/cjs/resolve/letter-spacing.js' {
  declare module.exports: $Exports<'twrnc/dist/cjs/resolve/letter-spacing'>;
}
declare module 'twrnc/dist/cjs/resolve/line-height.js' {
  declare module.exports: $Exports<'twrnc/dist/cjs/resolve/line-height'>;
}
declare module 'twrnc/dist/cjs/resolve/opacity.js' {
  declare module.exports: $Exports<'twrnc/dist/cjs/resolve/opacity'>;
}
declare module 'twrnc/dist/cjs/resolve/shadow.js' {
  declare module.exports: $Exports<'twrnc/dist/cjs/resolve/shadow'>;
}
declare module 'twrnc/dist/cjs/resolve/spacing.js' {
  declare module.exports: $Exports<'twrnc/dist/cjs/resolve/spacing'>;
}
declare module 'twrnc/dist/cjs/resolve/width-height.js' {
  declare module.exports: $Exports<'twrnc/dist/cjs/resolve/width-height'>;
}
declare module 'twrnc/dist/cjs/screens.js' {
  declare module.exports: $Exports<'twrnc/dist/cjs/screens'>;
}
declare module 'twrnc/dist/cjs/styles.js' {
  declare module.exports: $Exports<'twrnc/dist/cjs/styles'>;
}
declare module 'twrnc/dist/cjs/tw-config.js' {
  declare module.exports: $Exports<'twrnc/dist/cjs/tw-config'>;
}
declare module 'twrnc/dist/cjs/types.js' {
  declare module.exports: $Exports<'twrnc/dist/cjs/types'>;
}
declare module 'twrnc/dist/esm/cache.js' {
  declare module.exports: $Exports<'twrnc/dist/esm/cache'>;
}
declare module 'twrnc/dist/esm/ClassParser.js' {
  declare module.exports: $Exports<'twrnc/dist/esm/ClassParser'>;
}
declare module 'twrnc/dist/esm/create.js' {
  declare module.exports: $Exports<'twrnc/dist/esm/create'>;
}
declare module 'twrnc/dist/esm/helpers.js' {
  declare module.exports: $Exports<'twrnc/dist/esm/helpers'>;
}
declare module 'twrnc/dist/esm/hooks.js' {
  declare module.exports: $Exports<'twrnc/dist/esm/hooks'>;
}
declare module 'twrnc/dist/esm/index' {
  declare module.exports: $Exports<'twrnc/dist/esm'>;
}
declare module 'twrnc/dist/esm/index.js' {
  declare module.exports: $Exports<'twrnc/dist/esm'>;
}
declare module 'twrnc/dist/esm/parse-inputs.js' {
  declare module.exports: $Exports<'twrnc/dist/esm/parse-inputs'>;
}
declare module 'twrnc/dist/esm/plugin.js' {
  declare module.exports: $Exports<'twrnc/dist/esm/plugin'>;
}
declare module 'twrnc/dist/esm/resolve/borders.js' {
  declare module.exports: $Exports<'twrnc/dist/esm/resolve/borders'>;
}
declare module 'twrnc/dist/esm/resolve/color.js' {
  declare module.exports: $Exports<'twrnc/dist/esm/resolve/color'>;
}
declare module 'twrnc/dist/esm/resolve/flex.js' {
  declare module.exports: $Exports<'twrnc/dist/esm/resolve/flex'>;
}
declare module 'twrnc/dist/esm/resolve/font-family.js' {
  declare module.exports: $Exports<'twrnc/dist/esm/resolve/font-family'>;
}
declare module 'twrnc/dist/esm/resolve/font-size.js' {
  declare module.exports: $Exports<'twrnc/dist/esm/resolve/font-size'>;
}
declare module 'twrnc/dist/esm/resolve/inset.js' {
  declare module.exports: $Exports<'twrnc/dist/esm/resolve/inset'>;
}
declare module 'twrnc/dist/esm/resolve/letter-spacing.js' {
  declare module.exports: $Exports<'twrnc/dist/esm/resolve/letter-spacing'>;
}
declare module 'twrnc/dist/esm/resolve/line-height.js' {
  declare module.exports: $Exports<'twrnc/dist/esm/resolve/line-height'>;
}
declare module 'twrnc/dist/esm/resolve/opacity.js' {
  declare module.exports: $Exports<'twrnc/dist/esm/resolve/opacity'>;
}
declare module 'twrnc/dist/esm/resolve/shadow.js' {
  declare module.exports: $Exports<'twrnc/dist/esm/resolve/shadow'>;
}
declare module 'twrnc/dist/esm/resolve/spacing.js' {
  declare module.exports: $Exports<'twrnc/dist/esm/resolve/spacing'>;
}
declare module 'twrnc/dist/esm/resolve/width-height.js' {
  declare module.exports: $Exports<'twrnc/dist/esm/resolve/width-height'>;
}
declare module 'twrnc/dist/esm/screens.js' {
  declare module.exports: $Exports<'twrnc/dist/esm/screens'>;
}
declare module 'twrnc/dist/esm/styles.js' {
  declare module.exports: $Exports<'twrnc/dist/esm/styles'>;
}
declare module 'twrnc/dist/esm/tw-config.js' {
  declare module.exports: $Exports<'twrnc/dist/esm/tw-config'>;
}
declare module 'twrnc/dist/esm/types.js' {
  declare module.exports: $Exports<'twrnc/dist/esm/types'>;
}
