// flow-typed signature: 172edf25d9b578a486e24fa0b7b41a77
// flow-typed version: <<STUB>>/urql_v^2.2.3/flow_v0.182.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'urql'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'urql' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'urql/core/index.esm' {
  declare module.exports: any;
}

declare module 'urql/core' {
  declare module.exports: any;
}

declare module 'urql/dist/urql.es' {
  declare module.exports: any;
}

declare module 'urql/dist/urql' {
  declare module.exports: any;
}

declare module 'urql/dist/urql.min.es' {
  declare module.exports: any;
}

declare module 'urql/dist/urql.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'urql/core/index.esm.js' {
  declare module.exports: $Exports<'urql/core/index.esm'>;
}
declare module 'urql/core/index' {
  declare module.exports: $Exports<'urql/core'>;
}
declare module 'urql/core/index.js' {
  declare module.exports: $Exports<'urql/core'>;
}
declare module 'urql/dist/urql.es.js' {
  declare module.exports: $Exports<'urql/dist/urql.es'>;
}
declare module 'urql/dist/urql.js' {
  declare module.exports: $Exports<'urql/dist/urql'>;
}
declare module 'urql/dist/urql.min.es.js' {
  declare module.exports: $Exports<'urql/dist/urql.min.es'>;
}
declare module 'urql/dist/urql.min.js' {
  declare module.exports: $Exports<'urql/dist/urql.min'>;
}
