// flow-typed signature: b01f18f9c5b31c2c5f877c78a029a26a
// flow-typed version: <<STUB>>/@react-buddy/ide-toolbox_v^2.2.0/flow_v0.182.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-buddy/ide-toolbox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-buddy/ide-toolbox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-buddy/ide-toolbox/dist/index.esm' {
  declare module.exports: any;
}

declare module '@react-buddy/ide-toolbox/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-buddy/ide-toolbox/dist/index.esm.js' {
  declare module.exports: $Exports<'@react-buddy/ide-toolbox/dist/index.esm'>;
}
declare module '@react-buddy/ide-toolbox/dist/index' {
  declare module.exports: $Exports<'@react-buddy/ide-toolbox/dist'>;
}
declare module '@react-buddy/ide-toolbox/dist/index.js' {
  declare module.exports: $Exports<'@react-buddy/ide-toolbox/dist'>;
}
